# Generated by Django 5.0.4 on 2024-04-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.FloatField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_group', to='auth.group')),
            ],
            options={
                'verbose_name': 'Customer Detail',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_terms', models.CharField(blank=True, default='', max_length=200)),
                ('attention_to', models.CharField(blank=True, default='', max_length=200)),
                ('narration_internal', models.TextField(blank=True, default='', max_length=1000)),
                ('narration_external', models.TextField(blank=True, default='', max_length=1000)),
                ('invoice_amount', models.FloatField(default=0)),
                ('customer_full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_full_name', to='quotation.customer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_group', to='auth.group')),
            ],
            options={
                'verbose_name': 'Invoice Detail',
                'ordering': ['customer_full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_order', models.FloatField(default=0)),
                ('code', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('size', models.CharField(blank=True, default='', max_length=200)),
                ('packaging', models.CharField(blank=True, default='', max_length=200)),
                ('selling_rate', models.FloatField(default=0)),
                ('purchase_rate', models.FloatField(default=0)),
                ('unit', models.CharField(default='', max_length=200)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('total', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, default='', max_length=500)),
                ('sp_price', models.CharField(blank=True, default='', max_length=200)),
                ('stock', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_image')),
                ('last_edited_by', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='quotation.invoice')),
            ],
            options={
                'verbose_name': 'Item Detail',
                'ordering': ['invoice_id', 'entry_order'],
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('mobile_number', models.CharField(max_length=50)),
                ('land_line_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesman_group', to='auth.group')),
            ],
            options={
                'verbose_name': 'Salesman Detail',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='salesman_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesman_full_name', to='quotation.salesman'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['id', 'group'], name='quotation_i_id_e19b5d_idx'),
        ),
    ]
