# Generated by Django 5.0.4 on 2024-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True)),
                ('description_sheet', models.CharField(max_length=250, null=True)),
                ('description_stock', models.CharField(max_length=250, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('packaging', models.CharField(max_length=150, null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('cash_rate', models.FloatField(null=True)),
                ('sale_rate', models.FloatField(null=True)),
                ('purchase_rate', models.FloatField(null=True)),
                ('stock', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
