# Generated by Django 5.0.4 on 2024-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogsCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('type', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=500)),
                ('details', models.TextField(max_length=5000)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField()),
                ('type', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=500)),
                ('details', models.TextField(max_length=5000)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsLoginLogout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('user', models.CharField(max_length=500)),
                ('ip_address', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LogsSalesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_id', models.IntegerField()),
                ('type', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=500)),
                ('details', models.TextField(max_length=5000)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
